'use client'

import Link from 'next/link'

const NAVY = '#0D2C54'
const CORAL = '#FF7767'
const INK = '#2c3e50'
const MUTED = '#667085'

const pageStyle: React.CSSProperties = {
  background: '#fff',
  minHeight: '100vh',
  fontFamily: 'Raleway, sans-serif',
  color: INK,
}

const containerStyle: React.CSSProperties = {
  maxWidth: '760px',
  margin: '0 auto',
  padding: '40px 24px 96px',
}

const h1Style: React.CSSProperties = {
  fontSize: '34px',
  fontWeight: 800,
  color: NAVY,
  margin: '0 0 8px',
  letterSpacing: '-0.01em',
}

const h2Style: React.CSSProperties = {
  fontSize: '20px',
  fontWeight: 700,
  color: NAVY,
  margin: '40px 0 12px',
}

const pStyle: React.CSSProperties = {
  fontSize: '16px',
  lineHeight: 1.7,
  color: INK,
  margin: '0 0 16px',
}

const liStyle: React.CSSProperties = {
  fontSize: '16px',
  lineHeight: 1.7,
  color: INK,
  marginBottom: '8px',
}

const updatedStyle: React.CSSProperties = {
  fontSize: '14px',
  color: MUTED,
  margin: '0 0 32px',
}

function BackLink() {
  return (
    <Link
      href="/"
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: '6px',
        fontSize: '14px',
        fontWeight: 600,
        color: CORAL,
        textDecoration: 'none',
        marginBottom: '32px',
      }}
    >
      ← Back to Hostics
    </Link>
  )
}

export default function PrivacyPage() {
  return (
    <div style={pageStyle}>
      <div style={containerStyle}>
        <BackLink />

        <h1 style={h1Style}>Privacy Policy</h1>
        <p style={updatedStyle}>Last updated: May 29, 2026</p>

        <p style={pStyle}>
          This Privacy Policy explains how Hostics STR Analytics (&ldquo;Hostics,&rdquo; &ldquo;we,&rdquo;
          &ldquo;us,&rdquo; or &ldquo;our&rdquo;) collects, uses, and protects information when you use the
          Hostics web application and related services (the &ldquo;Service&rdquo;).
        </p>
        <p style={pStyle}>
          By using the Service, you agree to the collection and use of information in accordance with this
          Policy.
        </p>

        <h2 style={h2Style}>1. Who we are</h2>
        <p style={pStyle}>
          Hostics is an analytics dashboard for short-term rental owners. The Service lets you record and
          import booking and expense data for your rental properties and view financial reporting based on
          that data.
        </p>
        <p style={pStyle}>
          For any privacy-related questions or requests, contact us at{' '}
          <a href="mailto:hello@hostics.app" style={{ color: CORAL, fontWeight: 600 }}>hello@hostics.app</a>.
        </p>

        <h2 style={h2Style}>2. Information we collect</h2>
        <p style={pStyle}><strong>Information you provide directly:</strong></p>
        <ul>
          <li style={liStyle}>
            <strong>Account information:</strong> the email address you use to create your account, and your
            password (stored only in hashed form by our authentication provider — we never see or store your
            plain-text password).
          </li>
          <li style={liStyle}>
            <strong>Property and financial data:</strong> information you enter or import about your rental
            properties, bookings/reservations, and expenses. This may include property names and addresses,
            guest booking details, dates, amounts, payout figures, vendors, and similar records.
          </li>
          <li style={liStyle}>
            <strong>Billing information:</strong> when you subscribe to a paid plan, your payment is processed
            by our payment provider (Stripe). We do not collect or store your full payment card number; that
            information is handled directly by Stripe. We retain limited billing-related records such as your
            subscription tier, status, and billing email.
          </li>
        </ul>

        <p style={pStyle}><strong>Information about uploaded files:</strong></p>
        <p style={pStyle}>
          When you import data from a CSV or Excel file, the file is processed <strong>in your browser</strong>.
          We do <strong>not</strong> store the uploaded file itself on our servers. Only the data extracted from
          it (your bookings or expenses) is saved to your account, along with a small import-history record that
          includes the file&rsquo;s name, the type of import, the number of rows imported, and the date.
        </p>

        <p style={pStyle}><strong>Information collected automatically:</strong></p>
        <p style={pStyle}>
          Standard technical data necessary to operate the Service, such as log information generated by our
          hosting and infrastructure providers. We do not use the Service to build advertising profiles, and we
          do not sell personal information.
        </p>

        <h2 style={h2Style}>3. How we use information</h2>
        <p style={pStyle}>We use the information we collect to:</p>
        <ul>
          <li style={liStyle}>Provide, operate, and maintain the Service;</li>
          <li style={liStyle}>Authenticate you and secure your account;</li>
          <li style={liStyle}>Process subscriptions and payments;</li>
          <li style={liStyle}>Generate the financial reporting and analytics that are the core function of the Service;</li>
          <li style={liStyle}>Send you transactional messages (for example, account confirmations, billing notices, and trial reminders);</li>
          <li style={liStyle}>Respond to your support requests; and</li>
          <li style={liStyle}>Comply with legal obligations.</li>
        </ul>

        <h2 style={h2Style}>4. Service providers (sub-processors)</h2>
        <p style={pStyle}>
          We rely on a small number of trusted third-party providers to operate the Service. Each processes
          data only as needed to provide their function:
        </p>
        <ul>
          <li style={liStyle}>
            <strong>Supabase</strong> — authentication, database, and backend infrastructure (stores your
            account and the property/booking/expense data you enter).
          </li>
          <li style={liStyle}>
            <strong>Stripe</strong> — payment processing and subscription billing. Stripe handles your payment
            card information directly under its own privacy policy.
          </li>
          <li style={liStyle}>
            <strong>Postmark</strong> — delivery of transactional emails.
          </li>
        </ul>
        <p style={pStyle}>
          These providers maintain their own privacy and security practices. We encourage you to review their
          policies.
        </p>

        <h2 style={h2Style}>5. How we share information</h2>
        <p style={pStyle}>We do <strong>not</strong> sell your personal information. We share information only:</p>
        <ul>
          <li style={liStyle}>With the service providers listed above, to operate the Service;</li>
          <li style={liStyle}>If required by law, regulation, legal process, or enforceable governmental request;</li>
          <li style={liStyle}>To protect the rights, property, or safety of Hostics, our users, or others; or</li>
          <li style={liStyle}>In connection with a merger, acquisition, or sale of assets, in which case we will provide notice before your information becomes subject to a different privacy policy.</li>
        </ul>

        <h2 style={h2Style}>6. Data retention</h2>
        <p style={pStyle}>
          We retain your account and the data you enter for as long as your account is active. If you close your
          account or request deletion, we will delete your personal data within a reasonable period, except
          where we are required to retain certain records to comply with legal, tax, or accounting obligations.
        </p>

        <h2 style={h2Style}>7. Your rights and choices</h2>
        <p style={pStyle}>
          Depending on where you live, you may have rights regarding your personal information, including the
          right to access, correct, export, or delete it, and to object to or restrict certain processing.
        </p>
        <p style={pStyle}>
          To exercise any of these rights, contact us at{' '}
          <a href="mailto:hello@hostics.app" style={{ color: CORAL, fontWeight: 600 }}>hello@hostics.app</a>. We
          will respond within the timeframe required by applicable law.
        </p>

        <h2 style={h2Style}>8. Security</h2>
        <p style={pStyle}>
          We take reasonable technical and organizational measures to protect your information, and we rely on
          infrastructure providers that maintain industry-standard security practices. However, no method of
          transmission or storage is completely secure, and we cannot guarantee absolute security.
        </p>

        <h2 style={h2Style}>9. Children&rsquo;s privacy</h2>
        <p style={pStyle}>
          The Service is not directed to children under 18, and we do not knowingly collect personal information
          from children. If you believe a child has provided us with personal information, please contact us so
          we can delete it.
        </p>

        <h2 style={h2Style}>10. Changes to this Policy</h2>
        <p style={pStyle}>
          We may update this Privacy Policy from time to time. When we do, we will revise the &ldquo;Last
          updated&rdquo; date above. Material changes will be communicated through the Service or by email where
          appropriate. Your continued use of the Service after changes take effect constitutes acceptance of the
          revised Policy.
        </p>

        <h2 style={h2Style}>11. Contact us</h2>
        <p style={pStyle}>
          If you have questions about this Privacy Policy or our handling of your information, contact us at{' '}
          <a href="mailto:hello@hostics.app" style={{ color: CORAL, fontWeight: 600 }}>hello@hostics.app</a>.
        </p>
      </div>
    </div>
  )
}
