'use client'

import Link from 'next/link'

const NAVY = '#0D2C54'
const CORAL = '#FF7767'
const INK = '#2c3e50'
const MUTED = '#667085'

const pageStyle: React.CSSProperties = {
  background: '#fff',
  minHeight: '100vh',
  fontFamily: 'Raleway, sans-serif',
  color: INK,
}

const containerStyle: React.CSSProperties = {
  maxWidth: '760px',
  margin: '0 auto',
  padding: '40px 24px 96px',
}

const h1Style: React.CSSProperties = {
  fontSize: '34px',
  fontWeight: 800,
  color: NAVY,
  margin: '0 0 8px',
  letterSpacing: '-0.01em',
}

const h2Style: React.CSSProperties = {
  fontSize: '20px',
  fontWeight: 700,
  color: NAVY,
  margin: '40px 0 12px',
}

const pStyle: React.CSSProperties = {
  fontSize: '16px',
  lineHeight: 1.7,
  color: INK,
  margin: '0 0 16px',
}

const liStyle: React.CSSProperties = {
  fontSize: '16px',
  lineHeight: 1.7,
  color: INK,
  marginBottom: '8px',
}

const updatedStyle: React.CSSProperties = {
  fontSize: '14px',
  color: MUTED,
  margin: '0 0 32px',
}

function BackLink() {
  return (
    <Link
      href="/"
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: '6px',
        fontSize: '14px',
        fontWeight: 600,
        color: CORAL,
        textDecoration: 'none',
        marginBottom: '32px',
      }}
    >
      ← Back to Hostics
    </Link>
  )
}

export default function TermsPage() {
  return (
    <div style={pageStyle}>
      <div style={containerStyle}>
        <BackLink />

        <h1 style={h1Style}>Terms of Service</h1>
        <p style={updatedStyle}>Last updated: May 29, 2026</p>

        <p style={pStyle}>
          These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and use of the Hostics web
          application and related services (the &ldquo;Service&rdquo;), provided by Hostics STR Analytics
          (&ldquo;Hostics,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;).
        </p>
        <p style={pStyle}>
          By creating an account or using the Service, you agree to be bound by these Terms. If you do not
          agree, do not use the Service.
        </p>

        <h2 style={h2Style}>1. The Service</h2>
        <p style={pStyle}>
          Hostics is an analytics dashboard that lets short-term rental owners record and import booking and
          expense data and view financial reporting based on that data. We may update, change, or discontinue
          features of the Service at any time.
        </p>
        <p style={pStyle}>
          The Service provides informational and analytical tools only. <strong>It does not provide tax,
          accounting, legal, or financial advice.</strong> Any reports, figures, or summaries generated by the
          Service — including tax-category mappings — are for your convenience and should be independently
          verified. You are responsible for the accuracy of your own records and for consulting a qualified
          professional regarding your tax and financial obligations.
        </p>

        <h2 style={h2Style}>2. Your account</h2>
        <p style={pStyle}>
          To use the Service you must create an account and provide accurate information. You are responsible
          for:
        </p>
        <ul>
          <li style={liStyle}>Maintaining the confidentiality of your login credentials;</li>
          <li style={liStyle}>All activity that occurs under your account; and</li>
          <li style={liStyle}>Notifying us promptly of any unauthorized use.</li>
        </ul>
        <p style={pStyle}>You must be at least 18 years old to use the Service.</p>

        <h2 style={h2Style}>3. Subscriptions, trials, and billing</h2>
        <p style={pStyle}>
          <strong>Free trial.</strong> We may offer a free trial period. Unless you cancel before the trial
          ends, your subscription will begin and you will be charged according to the plan you selected.
        </p>
        <p style={pStyle}>
          <strong>Billing.</strong> Paid subscriptions are billed in advance on a recurring basis (monthly or
          annual, depending on the plan you choose) through our payment processor, Stripe. By subscribing, you
          authorize us to charge your payment method on a recurring basis until you cancel.
        </p>
        <p style={pStyle}>
          <strong>Price changes.</strong> We may change subscription prices. If we do, we will give you
          reasonable advance notice, and any change will apply to billing periods after the notice.
        </p>
        <p style={pStyle}>
          <strong>Cancellation.</strong> You may cancel your subscription at any time through your account&rsquo;s
          billing settings. Cancellation takes effect at the end of your current billing period, and you will
          retain access until then. Except where required by law, payments are non-refundable and we do not
          provide refunds or credits for partial billing periods.
        </p>
        <p style={pStyle}>
          <strong>Plan limits.</strong> Each plan includes limits (for example, on the number of properties).
          If your usage exceeds your plan&rsquo;s limits, you may be required to upgrade or may incur additional
          charges as described at the time of purchase.
        </p>

        <h2 style={h2Style}>4. Acceptable use</h2>
        <p style={pStyle}>You agree not to:</p>
        <ul>
          <li style={liStyle}>Use the Service for any unlawful purpose or in violation of these Terms;</li>
          <li style={liStyle}>Upload or enter data you do not have the right to use;</li>
          <li style={liStyle}>Attempt to gain unauthorized access to the Service, other accounts, or our systems;</li>
          <li style={liStyle}>Interfere with or disrupt the integrity or performance of the Service;</li>
          <li style={liStyle}>Reverse-engineer, copy, or resell the Service except as permitted by law; or</li>
          <li style={liStyle}>Use the Service to store or transmit malicious code.</li>
        </ul>
        <p style={pStyle}>We may suspend or terminate accounts that violate these Terms.</p>

        <h2 style={h2Style}>5. Your data</h2>
        <p style={pStyle}>
          As between you and Hostics, you own the data you enter into the Service. You grant us a limited
          license to store, process, and display that data solely to provide the Service to you.
        </p>
        <p style={pStyle}>
          We handle your data as described in our{' '}
          <Link href="/privacy" style={{ color: CORAL, fontWeight: 600 }}>Privacy Policy</Link>. You are
          responsible for keeping your own copies of important records; while we take reasonable measures to
          protect and preserve data, you should not rely on the Service as your sole system of record.
        </p>

        <h2 style={h2Style}>6. Intellectual property</h2>
        <p style={pStyle}>
          The Service, including its software, design, and content (excluding your data), is owned by Hostics
          and protected by intellectual property laws. These Terms do not grant you any right to our trademarks,
          logos, or branding.
        </p>

        <h2 style={h2Style}>7. Disclaimers</h2>
        <p style={pStyle}>
          The Service is provided &ldquo;as is&rdquo; and &ldquo;as available,&rdquo; without warranties of any
          kind, whether express or implied, including warranties of merchantability, fitness for a particular
          purpose, and non-infringement. We do not warrant that the Service will be uninterrupted, error-free,
          or that any data, calculation, or report will be accurate or complete.
        </p>

        <h2 style={h2Style}>8. Limitation of liability</h2>
        <p style={pStyle}>
          To the maximum extent permitted by law, Hostics will not be liable for any indirect, incidental,
          special, consequential, or punitive damages, or for any loss of profits, revenue, data, or goodwill,
          arising out of or related to your use of the Service.
        </p>
        <p style={pStyle}>
          To the maximum extent permitted by law, our total liability for any claim arising out of or related to
          the Service will not exceed the greater of (a) the amount you paid us for the Service in the twelve
          months before the claim, or (b) one hundred U.S. dollars (USD $100).
        </p>

        <h2 style={h2Style}>9. Indemnification</h2>
        <p style={pStyle}>
          You agree to indemnify and hold harmless Hostics from any claims, damages, losses, or expenses
          (including reasonable legal fees) arising out of your use of the Service, your data, or your violation
          of these Terms.
        </p>

        <h2 style={h2Style}>10. Termination</h2>
        <p style={pStyle}>
          You may stop using the Service at any time. We may suspend or terminate your access if you violate
          these Terms or if we discontinue the Service. Upon termination, your right to use the Service ends, and
          we may delete your data in accordance with our Privacy Policy and data-retention practices.
        </p>

        <h2 style={h2Style}>11. Governing law</h2>
        <p style={pStyle}>
          These Terms are governed by the laws of the Commonwealth of Pennsylvania, United States, without
          regard to its conflict-of-laws principles. You agree that any dispute arising out of or relating to
          these Terms or the Service will be subject to the exclusive jurisdiction of the state and federal
          courts located in Pennsylvania.
        </p>

        <h2 style={h2Style}>12. Changes to these Terms</h2>
        <p style={pStyle}>
          We may revise these Terms from time to time. When we do, we will update the &ldquo;Last updated&rdquo;
          date above. Material changes will be communicated through the Service or by email where appropriate.
          Your continued use of the Service after changes take effect constitutes acceptance of the revised
          Terms.
        </p>

        <h2 style={h2Style}>13. Contact us</h2>
        <p style={pStyle}>
          If you have questions about these Terms, contact us at{' '}
          <a href="mailto:hello@hostics.app" style={{ color: CORAL, fontWeight: 600 }}>hello@hostics.app</a>.
        </p>
      </div>
    </div>
  )
}
